### PR TITLE
Update "Getting Started" instructions

### PR DESCRIPTION
**Pull request by AndresCuervo**
This change:
- Does a little copy editing
- Adds GIFs going through some of the Xcode steps with more obtuse UI.

### CODE REVIEW

**Comment by AndresCuervo** [comment]
I signed it!

**Comment by AndresCuervo** [comment]
@judax thoughts?

**Comment by judax** [comment]
LGTM. Adding @mprafson as she was also involved in the update of the documentation.

**Comment by lincolnfrog** [comment]
This looks great, thank you!

**Pull request merged**
